### ISSUE TITLE
Unlink get_sdk_persist_dir() on uninstall

### ISSUE THREAD

**Issue by maxbaeumle** [pebble/pebble-tool#16]
[Uninstalling](https://github.com/pebble/pebble-tool/blob/master/pebble_tool/sdk/manager.py#L62) a SDK version should also remove [`get_sdk_persist_dir()`](https://github.com/pebble/pebble-tool/blob/master/pebble_tool/sdk/__init__.py#L34) for that version.
@jneubrand suggested adding an option to keep emulator data.

**Comment by maxbaeumle** [comment]
#17 makes this redundant.

**Comment by jneubrand** [comment]
:)
