### ISSUE TITLE
redirection via pipe doesn't work correctly for `pebble logs`.

### ISSUE THREAD

**Issue by jneubrand** [pebble/pebble-tool#24]
pebble logs --cloudpebble | cat
_yields:_

    [No response]

_after ^C:_

    ^Cclose failed in file object destructor:
    sys.excepthook is missing
    lost sys.stderr

=> **_Redirection via pipe is broken_**.

---

    pebble logs --cloudpebble 1>&2
_yields:_

    Waiting for phone to connect...
    Connected.

=> Redirection (here stdout to stderr) seems to work in general. I also tested redirection to a file, this **worked as expected**.

---

    pebble logs --cloudpebble
_yields:_

    Waiting for phone to connect...
    Connected.

=> Control case. **Works as expected.**

---

    pebble help | cat

_yields_

    usage: pebble [-h] [--version]
    
                  {analyze-size,transcribe,logs,data-logging,emu-accel,emu-control,kill,emu-time-format,emu-bt-connection,insert-pin,ping,emu-app-config,build,emu-tap,clean,screenshot,delete-pin,convert-project,repl,logout,wipe,sdk,emu-compass,new-project,install,emu-battery,login}
                  ...
    pebble: error: invalid choice: 'help' (choose from 'analyze-size', 'transcribe', 'logs', 'data-logging', 'emu-accel', 'emu-control', 'kill', 'emu-time-format', 'emu-bt-connection', 'insert-pin', 'ping', 'emu-app-config', 'build', 'emu-tap', 'clean', 'screenshot', 'delete-pin', 'convert-project', 'repl', 'logout', 'wipe', 'sdk', 'emu-compass', 'new-project', 'install', 'emu-battery', 'login')

=> **Works as expected.**

---

The problem seems to only affect `pebble logs`. Let me know if I can help out somehow.

**Comment by gregoiresage** [comment]
The 'problem' seems to be the `print(message)` in logs.py (line [63](https://github.com/pebble/pebble-tool/blob/master/pebble_tool/util/logs.py#L63) and [65](https://github.com/pebble/pebble-tool/blob/master/pebble_tool/util/logs.py#L65))
If you replace  `print(message)` by `sys.stdout.write(message + '\n')` this problem is gone

**Comment by jneubrand** [comment]
Huh, weird. Want me to open a PR?
